/**
 * Fictional demo fixtures only — no real patient health information.
 */
import type {
  AppPreferences,
  EvidenceSource,
  ExtractedHealthItem,
  HealthProfile,
  SafetyAlert,
  Supplement,
  SupplementCheck,
  UploadedDocument,
  User,
} from './models';

export const DEMO_USER: User = {
  id: 'user-demo-001',
  email: 'olivia.harper@email.com',
  fullName: 'Olivia Harper',
  dateOfBirth: '1997-03-14',
  biologicalSex: 'female',
  country: 'United States',
  onboardingCompleted: false,
  createdAt: '2026-05-01T12:00:00.000Z',
};

export const DEMO_PREFERENCES: AppPreferences = {
  goals: ['General wellness'],
  dietary: ['No restrictions'],
  lifestyle: ['Exercise regularly', 'Athlete / Active'],
  safetyAlertsEnabled: true,
  insightsEnabled: true,
  appearance: 'light',
  language: 'English (US)',
};

export const DEMO_HEALTH_PROFILE: HealthProfile = {
  id: 'profile-demo-001',
  userId: DEMO_USER.id,
  readiness: 'strong',
  readinessNote:
    "You've provided the key information BioCross uses for supplement safety checks.",
  lastUpdatedAt: '2026-05-07T14:00:00.000Z',
  items: [
    {
      id: 'cond-1',
      category: 'condition',
      name: 'Congenital heart disease',
      details: 'D-Transposition of the Great Arteries',
      status: 'confirmed',
      confirmedAt: '2026-05-07T14:10:00.000Z',
      sourceDocumentId: 'doc-1',
    },
    {
      id: 'med-1',
      category: 'medication',
      name: 'Losartan',
      details: '50 mg daily',
      status: 'confirmed',
      confirmedAt: '2026-05-07T14:10:00.000Z',
      sourceDocumentId: 'doc-1',
      metadata: { dosage: '50 mg daily' },
    },
    {
      id: 'med-2',
      category: 'medication',
      name: 'Aspirin',
      details: '81 mg daily',
      status: 'confirmed',
      confirmedAt: '2026-05-07T14:10:00.000Z',
      sourceDocumentId: 'doc-1',
    },
    {
      id: 'med-3',
      category: 'medication',
      name: 'Digoxin',
      details: '125 mcg daily',
      status: 'confirmed',
      confirmedAt: '2026-05-07T14:10:00.000Z',
      sourceDocumentId: 'doc-1',
    },
    {
      id: 'med-4',
      category: 'medication',
      name: 'Amoxicillin',
      details: '500 mg before dental procedures',
      status: 'confirmed',
      confirmedAt: '2026-05-07T14:10:00.000Z',
      sourceDocumentId: 'doc-1',
    },
    {
      id: 'sup-1',
      category: 'supplement',
      name: 'Vitamin D3',
      details: '2000 IU daily',
      status: 'confirmed',
      confirmedAt: '2026-05-02T10:00:00.000Z',
    },
    {
      id: 'sup-2',
      category: 'supplement',
      name: 'Omega-3 Fish Oil',
      details: '1200 mg',
      status: 'confirmed',
      confirmedAt: '2026-05-02T10:00:00.000Z',
    },
    {
      id: 'sup-3',
      category: 'supplement',
      name: 'Magnesium Glycinate',
      details: '200 mg',
      status: 'confirmed',
      confirmedAt: '2026-05-02T10:00:00.000Z',
    },
    {
      id: 'all-1',
      category: 'allergy',
      name: 'No known allergies (NKDA)',
      status: 'confirmed',
      confirmedAt: '2026-05-07T14:10:00.000Z',
      sourceDocumentId: 'doc-1',
    },
    {
      id: 'all-2',
      category: 'allergy',
      name: 'Penicillin (historical note under review)',
      details: 'Rash — pending confirmation',
      status: 'pending_review',
    },
    {
      id: 'proc-1',
      category: 'procedure',
      name: 'Pulmonary valve replacement',
      details: '2016',
      status: 'confirmed',
      confirmedAt: '2026-05-07T14:10:00.000Z',
      sourceDocumentId: 'doc-1',
      metadata: { year: '2016' },
    },
    {
      id: 'proc-2',
      category: 'procedure',
      name: 'Arterial switch operation',
      details: 'Childhood',
      status: 'confirmed',
      confirmedAt: '2026-05-07T14:10:00.000Z',
    },
    {
      id: 'proc-3',
      category: 'procedure',
      name: 'Cardiac catheterization',
      details: '2022',
      status: 'confirmed',
      confirmedAt: '2026-05-03T09:00:00.000Z',
    },
    {
      id: 'proc-4',
      category: 'procedure',
      name: 'Pacemaker evaluation',
      details: '2024',
      status: 'confirmed',
      confirmedAt: '2026-05-03T09:00:00.000Z',
    },
    {
      id: 'lab-1',
      category: 'lab_result',
      name: 'INR monitoring',
      details: 'Stable range noted in records',
      status: 'confirmed',
      confirmedAt: '2026-05-04T11:00:00.000Z',
    },
    {
      id: 'lab-2',
      category: 'lab_result',
      name: 'Lipid panel',
      details: 'Within target',
      status: 'confirmed',
      confirmedAt: '2026-05-04T11:00:00.000Z',
    },
    {
      id: 'life-1',
      category: 'lifestyle',
      name: 'Exercise regularly',
      status: 'confirmed',
    },
    {
      id: 'change-1',
      category: 'recent_change',
      name: 'Medication dose adjustment',
      details: 'Losartan reviewed May 2026',
      status: 'not_reviewed',
    },
  ],
};

export const DEMO_DOCUMENT: UploadedDocument = {
  id: 'doc-1',
  fileName: 'Boston_Childrens_Visit_Summary.pdf',
  mimeType: 'application/pdf',
  sizeBytes: 1_200_000,
  pageCount: 12,
  uploadedAt: '2026-05-07T09:35:00.000Z',
  status: 'extracted',
};

export const DEMO_EXTRACTED_ITEMS: ExtractedHealthItem[] = [
  {
    id: 'ext-1',
    documentId: 'doc-1',
    category: 'condition',
    name: 'Congenital heart disease',
    details: 'D-Transposition of the Great Arteries',
    status: 'ready',
  },
  {
    id: 'ext-2',
    documentId: 'doc-1',
    category: 'procedure',
    name: 'Pulmonary valve replacement',
    details: '2016',
    status: 'ready',
  },
  {
    id: 'ext-3',
    documentId: 'doc-1',
    category: 'medication',
    name: 'Losartan',
    details: '50 mg daily',
    status: 'ready',
  },
  {
    id: 'ext-4',
    documentId: 'doc-1',
    category: 'medication',
    name: 'Aspirin',
    details: '81 mg daily',
    status: 'ready',
  },
  {
    id: 'ext-5',
    documentId: 'doc-1',
    category: 'medication',
    name: 'Digoxin',
    details: '125 mcg daily',
    status: 'ready',
  },
  {
    id: 'ext-6',
    documentId: 'doc-1',
    category: 'medication',
    name: 'Amoxicillin',
    details: '500 mg before dental procedures',
    status: 'ready',
  },
  {
    id: 'ext-7',
    documentId: 'doc-1',
    category: 'allergy',
    name: 'No known allergies (NKDA)',
    status: 'ready',
  },
  {
    id: 'ext-8',
    documentId: 'doc-1',
    category: 'lab_result',
    name: 'Kidney function labs',
    details: 'Multiple results found.',
    status: 'needs_detail',
    needsDetailReason: 'Multiple results found',
  },
  {
    id: 'ext-9',
    documentId: 'doc-1',
    category: 'lab_result',
    name: 'Liver enzyme results',
    details: 'Multiple results found.',
    status: 'needs_detail',
    needsDetailReason: 'Multiple results found',
  },
];

export const SUPPLEMENT_CATALOG: Supplement[] = [
  {
    id: 'sup-catalog-vitd',
    name: 'Vitamin D3',
    brand: 'PureHealth Essentials',
    dosage: '4000 IU (Cholecalciferol)',
    form: 'Softgel',
    barcode: '012345678905',
    ingredients: [
      { id: 'ing-d3', name: 'Vitamin D3 (Cholecalciferol)', amount: '4000 IU', isActive: true },
      { id: 'ing-oil', name: 'Olive oil', isActive: false },
    ],
  },
  {
    id: 'sup-catalog-mag',
    name: 'Magnesium Glycinate',
    brand: 'PureHealth Essentials',
    dosage: '200 mg per serving',
    form: 'Capsule',
    barcode: '012345678912',
    ingredients: [
      { id: 'ing-mag', name: 'Magnesium (as Magnesium Glycinate)', amount: '200 mg', isActive: true },
      { id: 'ing-hyp', name: 'Hypromellose (Capsule)', isActive: false },
      { id: 'ing-rice', name: 'Rice Flour', isActive: false },
    ],
  },
  {
    id: 'sup-catalog-ash',
    name: 'Ashwagandha',
    brand: 'CalmRoot Botanicals',
    dosage: '500 mg',
    form: 'Capsule',
    barcode: '012345678929',
    ingredients: [
      { id: 'ing-ash', name: 'Ashwagandha root extract', amount: '500 mg', isActive: true },
    ],
  },
  {
    id: 'sup-catalog-sjw',
    name: "St. John's Wort",
    brand: 'HerbField',
    dosage: '300 mg',
    form: 'Capsule',
    barcode: '012345678936',
    ingredients: [
      { id: 'ing-sjw', name: "St. John's Wort extract", amount: '300 mg', isActive: true },
    ],
  },
  {
    id: 'sup-catalog-testo',
    name: 'TestoMax 9000',
    brand: 'Prime Labs',
    dosage: '2 Capsules',
    form: 'Dietary Supplement',
    barcode: '012345678943',
    ingredients: [
      { id: 'ing-hge', name: 'Horny Goat Weed (Epimedium)', amount: '500 mg', isActive: true },
      { id: 'ing-yoh', name: 'Yohimbe Extract', amount: '50 mg', isActive: true },
      { id: 'ing-bit', name: 'Bitter Orange Extract (Synephrine)', amount: '30 mg', isActive: true },
      { id: 'ing-zinc', name: 'Zinc', amount: '15 mg', isActive: true },
    ],
  },
  {
    id: 'sup-catalog-omega',
    name: 'Omega-3 Fish Oil 1200mg',
    brand: 'OceanPure Supplements',
    dosage: '1200 mg',
    form: 'Softgel',
    barcode: '012345678950',
    ingredients: [
      { id: 'ing-epa', name: 'EPA', amount: '400 mg', isActive: true },
      { id: 'ing-dha', name: 'DHA', amount: '300 mg', isActive: true },
    ],
  },
  {
    id: 'sup-catalog-turmeric',
    name: 'Turmeric Curcumin',
    brand: 'GoldenRoot',
    dosage: '1000 mg',
    form: 'Capsule',
    barcode: '012345678967',
    ingredients: [
      { id: 'ing-tur', name: 'Turmeric root extract', amount: '1000 mg', isActive: true },
    ],
  },
  {
    id: 'sup-catalog-zinc',
    name: 'Zinc',
    brand: 'PureHealth Essentials',
    dosage: '25 mg',
    form: 'Tablet',
    barcode: '012345678974',
    ingredients: [{ id: 'ing-zn', name: 'Zinc', amount: '25 mg', isActive: true }],
  },
];

export const DEMO_EVIDENCE: EvidenceSource[] = [
  {
    id: 'ev-1',
    source: 'NIH / MedlinePlus',
    publication: 'Yohimbe',
    publicationDate: '2024-11-12',
    studyType: 'Monograph / established interaction summary',
    relevantFinding:
      'Yohimbe may raise blood pressure and heart rate and can interact with cardiovascular medications.',
    evidenceStrength: 'established',
    linkOrIdentifier: 'https://medlineplus.gov/druginfo/natural/759.html',
    retrievedAt: '2026-05-01T00:00:00.000Z',
  },
  {
    id: 'ev-2',
    source: 'FDA',
    publication: 'Dietary Supplement Ingredient Advisories',
    publicationDate: '2023-06-01',
    studyType: 'Regulatory advisory',
    relevantFinding:
      'Bitter orange (synephrine) has been associated with cardiovascular effects including elevated blood pressure.',
    evidenceStrength: 'established',
    linkOrIdentifier: 'FDA-bitter-orange-advisory',
    retrievedAt: '2026-05-01T00:00:00.000Z',
  },
  {
    id: 'ev-3',
    source: 'NIH ODS',
    publication: 'Magnesium Fact Sheet for Health Professionals',
    publicationDate: '2025-03-01',
    studyType: 'Evidence review',
    relevantFinding:
      'Magnesium glycinate is a commonly used form with generally favorable tolerability at typical supplemental doses.',
    evidenceStrength: 'moderate',
    linkOrIdentifier: 'ODS-magnesium',
    retrievedAt: '2026-05-01T00:00:00.000Z',
  },
  {
    id: 'ev-4',
    source: 'Mayo Clinic',
    publication: "St. John's wort",
    publicationDate: '2025-01-15',
    studyType: 'Clinical overview',
    relevantFinding:
      "St. John's wort can interact with many medications and may affect heart-related drug metabolism.",
    evidenceStrength: 'established',
    linkOrIdentifier: 'mayo-sjw',
    retrievedAt: '2026-05-01T00:00:00.000Z',
  },
];

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

export const DEMO_CHECKS: SupplementCheck[] = [
  {
    id: 'check-vitd',
    userId: DEMO_USER.id,
    supplement: SUPPLEMENT_CATALOG[0],
    checkedAt: daysAgo(2),
    riskLevel: 'low',
    headline: 'No Known Conflicts',
    summary:
      'No known conflicts were identified based on your current health profile and the information available to BioCross.',
    findings: [
      {
        id: 'f-vitd-1',
        severity: 'low',
        title: 'Interactions (0)',
        summary: 'No known interactions with your confirmed medications or conditions.',
        whatWeFound: 'No established interactions identified for Vitamin D3 at the checked dose.',
        whyItMatters:
          'Knowing there are no known conflicts based on your current profile helps you make an informed choice.',
        evidenceIds: [],
        discussWithProvider: 'Confirm vitamin D dosing with your healthcare provider if levels are being monitored.',
        category: 'interaction',
      },
    ],
    evidence: [],
    tips: [
      'Take with food containing some fat for better absorption.',
      'Keep your healthcare provider informed about supplements you take.',
      'Results may change if your health information changes.',
    ],
    disclaimer:
      'BioCross provides informational insights, not medical advice. Always talk to your healthcare provider with any concerns.',
    profileSnapshotNote: 'Analyzed against your health profile as of check time.',
  },
  {
    id: 'check-ash',
    userId: DEMO_USER.id,
    supplement: SUPPLEMENT_CATALOG[2],
    checkedAt: daysAgo(5),
    riskLevel: 'caution',
    headline: 'Use Caution',
    summary: 'Something to review based on your health profile.',
    findings: [
      {
        id: 'f-ash-1',
        severity: 'caution',
        title: 'Condition relevance',
        summary: 'Ashwagandha may warrant caution with certain heart-related conditions.',
        whatWeFound: 'Some reports suggest ashwagandha may affect blood pressure or heart rhythm in sensitive individuals.',
        whyItMatters: 'Your profile includes congenital heart disease, so extra review is warranted.',
        triggeredByProfileItemId: 'cond-1',
        triggeredByProfileItemLabel: 'Congenital heart disease',
        ingredientName: 'Ashwagandha root extract',
        evidenceIds: [],
        discussWithProvider: 'Ask your cardiology team before starting ashwagandha.',
        category: 'condition',
      },
    ],
    evidence: [],
    tips: ['Do not start a new supplement without checking with your care team.', 'Monitor how you feel if already taking it.'],
    disclaimer:
      'BioCross provides informational insights, not medical advice. Always talk to your healthcare provider with any concerns.',
    profileSnapshotNote: 'Analyzed against your health profile as of check time.',
  },
  {
    id: 'check-sjw',
    userId: DEMO_USER.id,
    supplement: SUPPLEMENT_CATALOG[3],
    checkedAt: daysAgo(7),
    riskLevel: 'high',
    headline: 'High Risk',
    summary: 'This supplement may not be safe for you. We found potential conflicts.',
    findings: [
      {
        id: 'f-sjw-1',
        severity: 'high',
        title: 'Potential medication interaction',
        summary: "St. John's Wort may interact with medications in your profile.",
        whatWeFound: "St. John's Wort can affect how the body processes many medications.",
        whyItMatters: 'Interactions may change medication effectiveness or side effects.',
        triggeredByProfileItemId: 'med-1',
        triggeredByProfileItemLabel: 'Losartan',
        ingredientName: "St. John's Wort extract",
        evidenceIds: ['ev-4'],
        discussWithProvider: 'Do not combine with prescription medicines without clinician guidance.',
        category: 'interaction',
      },
    ],
    evidence: [DEMO_EVIDENCE[3]],
    tips: ['Do not take this supplement.', 'Talk to your healthcare provider about safer alternatives.'],
    disclaimer:
      'BioCross provides informational insights, not medical advice. Always talk to your healthcare provider with any concerns.',
    profileSnapshotNote: 'Analyzed against your health profile as of check time.',
    newerInfoAvailable: true,
  },
];

export const DEMO_HIGH_RISK_CHECK: SupplementCheck = {
  id: 'check-testomax',
  userId: DEMO_USER.id,
  supplement: SUPPLEMENT_CATALOG[4],
  checkedAt: new Date().toISOString(),
  riskLevel: 'high',
  headline: 'High Risk',
  summary: 'This supplement may not be safe for you. We found 3 concerns.',
  findings: [
    {
      id: 'f-tm-1',
      severity: 'high',
      title: 'May interact with your medications',
      summary: 'Horny Goat Weed (Epimedium) may increase effects of Losartan.',
      whatWeFound: 'Horny Goat Weed (Epimedium) → May increase effects of Losartan.',
      whyItMatters: 'Combining products that affect blood pressure can raise the chance of dizziness or low blood pressure.',
      triggeredByProfileItemId: 'med-1',
      triggeredByProfileItemLabel: 'Losartan (50 mg daily)',
      ingredientName: 'Horny Goat Weed (Epimedium)',
      evidenceIds: ['ev-1'],
      discussWithProvider: 'Ask whether any testosterone-support or stimulant blends are appropriate for you.',
      category: 'interaction',
    },
    {
      id: 'f-tm-2',
      severity: 'high',
      title: 'May worsen your health condition',
      summary: 'Yohimbe Extract may increase blood pressure and heart rate.',
      whatWeFound: 'Yohimbe Extract → May increase blood pressure and heart rate.',
      whyItMatters: 'Your profile includes congenital heart disease; stimulants that raise heart rate may be concerning.',
      triggeredByProfileItemId: 'cond-1',
      triggeredByProfileItemLabel: 'Congenital heart disease',
      ingredientName: 'Yohimbe Extract',
      evidenceIds: ['ev-1'],
      discussWithProvider: 'Review stimulant ingredients with your cardiology team before use.',
      category: 'condition',
    },
    {
      id: 'f-tm-3',
      severity: 'caution',
      title: 'Contains stimulants',
      summary: 'Bitter Orange Extract (Synephrine) — may affect heart rhythm.',
      whatWeFound: 'Bitter Orange Extract (Synephrine) → Stimulant – may affect heart rhythm.',
      whyItMatters: 'Stimulant ingredients can add cardiovascular load even at labeled doses.',
      ingredientName: 'Bitter Orange Extract (Synephrine)',
      evidenceIds: ['ev-2'],
      discussWithProvider: 'Ask about safer alternatives that avoid synephrine and yohimbe.',
      category: 'ingredient',
    },
  ],
  evidence: [DEMO_EVIDENCE[0], DEMO_EVIDENCE[1]],
  tips: [
    'Do not take this supplement.',
    'Talk to your healthcare provider about safer alternatives.',
    'Keep monitoring your health.',
  ],
  disclaimer:
    'BioCross provides informational insights, not medical advice. Always talk to your healthcare provider with any concerns.',
  profileSnapshotNote: 'We analyzed this supplement against your health profile.',
};

export const DEMO_LOW_RISK_CHECK: SupplementCheck = {
  id: 'check-mag-fresh',
  userId: DEMO_USER.id,
  supplement: SUPPLEMENT_CATALOG[1],
  checkedAt: new Date().toISOString(),
  riskLevel: 'low',
  headline: 'No Known Conflicts',
  summary:
    'No known conflicts were identified based on your current health profile and the information available to BioCross.',
  findings: [
    {
      id: 'f-mag-1',
      severity: 'low',
      title: 'Interactions (0)',
      summary: 'No known interactions with your confirmed medications or conditions.',
      whatWeFound: 'No established interactions identified for Magnesium Glycinate at the checked dose.',
      whyItMatters: 'Absence of known conflicts based on available profile data is reassuring—but not a guarantee.',
      evidenceIds: ['ev-3'],
      discussWithProvider: 'Confirm magnesium use if you have kidney concerns or take other minerals.',
      category: 'interaction',
    },
    {
      id: 'f-mag-2',
      severity: 'info',
      title: '3 ingredients analyzed',
      summary: 'Magnesium Glycinate, Hypromellose, and Rice Flour — no known concerns.',
      whatWeFound: 'All listed ingredients were reviewed against your confirmed profile items.',
      whyItMatters: 'Reviewing inactive ingredients helps catch fillers and capsule materials that sometimes matter for allergies.',
      evidenceIds: ['ev-3'],
      discussWithProvider: 'Share the full Supplement Facts panel if your clinician wants product specifics.',
      category: 'general',
    },
  ],
  evidence: [DEMO_EVIDENCE[2]],
  tips: [
    'Take with food if magnesium upsets your stomach.',
    'Separate from certain medications if your pharmacist recommends it.',
    'Results may change if your health information changes.',
  ],
  disclaimer:
    'BioCross provides informational insights, not medical advice. Always talk to your healthcare provider with any concerns.',
  profileSnapshotNote: 'We analyzed this supplement against your health profile.',
};

export const DEMO_MORE_INFO_CHECK: SupplementCheck = {
  id: 'check-more-info',
  userId: DEMO_USER.id,
  supplement: {
    id: 'sup-incomplete',
    name: 'Unverified Formula',
    brand: 'Label partially readable',
    ingredients: [],
  },
  checkedAt: new Date().toISOString(),
  riskLevel: 'more_info',
  headline: 'More Information Needed',
  summary:
    "We couldn't confidently complete this safety check with the information currently available.",
  findings: [
    {
      id: 'f-more-1',
      severity: 'more_info',
      title: 'Ingredient dosage could not be identified',
      summary: 'Supplement Facts lines were incomplete or unreadable.',
      whatWeFound: 'Barcode/label data did not resolve to a complete product formula with dosages.',
      whyItMatters:
        'Without enough product detail, BioCross will not invent a positive or negative safety result.',
      evidenceIds: [],
      discussWithProvider:
        'Bring the bottle or a clear Supplement Facts photo to your pharmacist or clinician if you need guidance sooner.',
      category: 'general',
    },
    {
      id: 'f-more-2',
      severity: 'more_info',
      title: 'What we need',
      summary: 'A clearer label photo, verified ingredient list, or updated health-profile details.',
      whatWeFound: 'Formulation verification is required before a safety result can be issued.',
      whyItMatters:
        'Missing information is not the same as “no known conflict.” BioCross keeps those outcomes separate.',
      evidenceIds: [],
      discussWithProvider: 'Ask your care team before starting any unverified product.',
      category: 'general',
    },
  ],
  evidence: [],
  tips: [
    'Photograph the Supplement Facts panel',
    'Update or confirm your medications',
    'Search by name if the barcode is unclear',
  ],
  disclaimer:
    'BioCross provides informational insights, not medical advice. Always talk to your healthcare provider with any concerns.',
  profileSnapshotNote: 'Analysis paused due to insufficient product or profile information.',
};

/** @deprecated Use DEMO_MORE_INFO_CHECK */
export const DEMO_UNKNOWN_CHECK = DEMO_MORE_INFO_CHECK;

export const DEMO_ALERTS: SafetyAlert[] = [
  {
    id: 'alert-1',
    type: 'recall',
    priority: 'urgent',
    title: 'Recall: Omega-3 Fish Oil 1200mg',
    description:
      'This product has been recalled due to potential contamination with harmful bacteria.',
    date: '2025-10-26',
    source: 'OceanPure Supplements / FDA',
    personalizedLabel: 'High Priority',
    isRead: false,
    relatedSupplementId: 'sup-catalog-omega',
  },
  {
    id: 'alert-2',
    type: 'interaction',
    priority: 'urgent',
    title: 'New Interaction Found',
    description:
      'Turmeric may interact with your blood thinner (Warfarin) and increase bleeding risk.',
    date: '2025-10-24',
    personalizedLabel: 'May Affect Your Medications',
    isRead: false,
  },
  {
    id: 'alert-3',
    type: 'research',
    priority: 'informational',
    title: 'New Study on Vitamin D & Immunity',
    description: 'New research suggests Vitamin D may play a key role in immune system support.',
    date: '2025-10-22',
    source: 'NIH',
    personalizedLabel: 'Informational',
    isRead: false,
  },
  {
    id: 'alert-4',
    type: 'regulatory',
    priority: 'urgent',
    title: 'FDA Issues Warning on Certain Ashwagandha Products',
    description: 'Some supplements found to contain elevated levels of lead.',
    date: '2025-10-26',
    source: 'FDA',
    isRead: false,
  },
  {
    id: 'alert-5',
    type: 'interaction',
    priority: 'personalized',
    title: "New Interaction Data: St. John's Wort",
    description: 'Updated interaction information relevant to heart medications in your profile.',
    date: '2025-10-24',
    personalizedLabel: 'May Affect Your Medications',
    isRead: false,
  },
  {
    id: 'alert-6',
    type: 'research',
    priority: 'personalized',
    title: 'CoQ10 – New Study Results',
    description: 'New findings focused on heart health benefits that may relate to your condition.',
    date: '2025-10-20',
    personalizedLabel: 'Relevant to Your Heart Condition',
    isRead: false,
  },
  {
    id: 'alert-7',
    type: 'system',
    priority: 'informational',
    title: 'BioCross App Update',
    description: 'New features and performance improvements.',
    date: '2025-10-18',
    isRead: true,
  },
  {
    id: 'alert-8',
    type: 'research',
    priority: 'informational',
    title: 'Omega-3 and heart health overview',
    description: 'Latest research summary from trusted sources.',
    date: '2025-10-22',
    source: 'NIH',
    isRead: true,
  },
  {
    id: 'alert-9',
    type: 'research',
    priority: 'informational',
    title: 'Magnesium forms compared',
    description: 'Clinical overview of common magnesium supplements.',
    date: '2025-10-21',
    source: 'Mayo Clinic',
    isRead: true,
  },
  {
    id: 'alert-10',
    type: 'research',
    priority: 'informational',
    title: 'Vitamin C evidence update',
    description: 'What current research says about routine supplementation.',
    date: '2025-10-19',
    source: 'Harvard Health',
    isRead: true,
  },
];

export const POPULAR_SEARCHES = ['Vitamin D', 'Magnesium', 'Ashwagandha', 'Omega-3', 'Zinc'] as const;
