services:
  db:
    image: postgres:16-alpine
    container_name: rme-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rate_my_employer
    ports:
      - '5432:5432'
    volumes:
      - rme_pg_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

volumes:
  rme_pg_data:
