use crate::academic::types::{AcademicContentTier, IndexedSource};

/// Seed academic index for AreoOS Machu / Surf.
/// Sources are real educational repositories with structured metadata —
/// not open-web SEO listings.
pub fn academic_corpus() -> Vec<IndexedSource> {
    vec![
        // —— Plate Tectonics ——
        IndexedSource {
            id: "usgs-plate-tectonics-intro".into(),
            title: "What is Plate Tectonics?".into(),
            url: "https://www.usgs.gov/faqs/what-plate-tectonics".into(),
            domain: "usgs.gov".into(),
            publisher: "U.S. Geological Survey".into(),
            content_tier: AcademicContentTier::VerifiedReference,
            grade_min: 6,
            grade_max: 12,
            abstract_text: "Plate tectonics is the unifying theory that Earth’s outer shell is divided into several plates that glide over the mantle. Plate motion explains earthquakes, volcanoes, mountain building, and the slow reshaping of continents and ocean basins over geologic time.".into(),
            vocabulary: vec![
                "lithosphere".into(),
                "asthenosphere".into(),
                "mantle".into(),
                "convergent boundary".into(),
                "divergent boundary".into(),
                "transform boundary".into(),
            ],
            citation: "U.S. Geological Survey. \"What is Plate Tectonics?\" USGS FAQs.".into(),
            topics: vec!["plate tectonics".into(), "earth science".into(), "geology".into()],
            keywords: vec![
                "plates".into(),
                "earthquakes".into(),
                "volcanoes".into(),
                "continental drift".into(),
            ],
            base_legitimacy: 96,
        },
        IndexedSource {
            id: "usgs-how-plates-move".into(),
            title: "How Do Plates Move?".into(),
            url: "https://www.usgs.gov/faqs/how-do-plates-move".into(),
            domain: "usgs.gov".into(),
            publisher: "U.S. Geological Survey".into(),
            content_tier: AcademicContentTier::AuthoritativeResearch,
            grade_min: 7,
            grade_max: 12,
            abstract_text: "Earth’s tectonic plates are driven by heat from the planet’s interior. Convection in the mantle, slab pull at subduction zones, and ridge push at mid-ocean ridges work together so plates creep a few centimeters each year—about as fast as fingernails grow.".into(),
            vocabulary: vec![
                "convection".into(),
                "subduction".into(),
                "mid-ocean ridge".into(),
                "slab pull".into(),
                "ridge push".into(),
            ],
            citation: "U.S. Geological Survey. \"How Do Plates Move?\" USGS FAQs.".into(),
            topics: vec!["plate tectonics".into(), "mantle convection".into()],
            keywords: vec!["plates".into(), "move".into(), "convection".into(), "subduction".into()],
            base_legitimacy: 96,
        },
        IndexedSource {
            id: "natgeo-edu-plate-tectonics".into(),
            title: "Plate Tectonics — National Geographic Education".into(),
            url: "https://education.nationalgeographic.org/resource/plate-tectonics/".into(),
            domain: "education.nationalgeographic.org".into(),
            publisher: "National Geographic Society".into(),
            content_tier: AcademicContentTier::EducationalMagazine,
            grade_min: 5,
            grade_max: 10,
            abstract_text: "A classroom-ready overview of plate tectonics: how Earth’s crust is broken into plates, what happens at plate boundaries, and why the theory replaced earlier ideas about fixed continents. Includes maps and vocabulary suited for middle grades upward.".into(),
            vocabulary: vec![
                "crust".into(),
                "plate boundary".into(),
                "Pangaea".into(),
                "seafloor spreading".into(),
            ],
            citation: "National Geographic Society. \"Plate Tectonics.\" National Geographic Education.".into(),
            topics: vec!["plate tectonics".into(), "earth science".into()],
            keywords: vec!["plates".into(), "boundaries".into(), "pangaea".into(), "geology".into()],
            base_legitimacy: 92,
        },
        IndexedSource {
            id: "britannica-plate-tectonics".into(),
            title: "Plate Tectonics — Encyclopædia Britannica".into(),
            url: "https://www.britannica.com/science/plate-tectonics".into(),
            domain: "britannica.com".into(),
            publisher: "Encyclopædia Britannica".into(),
            content_tier: AcademicContentTier::VerifiedReference,
            grade_min: 8,
            grade_max: 12,
            abstract_text: "Britannica’s reference article on plate tectonics covers the historical development of the theory, types of plate margins, and evidence from paleomagnetism, fossil distributions, and ocean-floor mapping that confirmed continental drift and seafloor spreading.".into(),
            vocabulary: vec![
                "paleomagnetism".into(),
                "continental drift".into(),
                "Wilson cycle".into(),
                "orogeny".into(),
            ],
            citation: "Encyclopædia Britannica. \"Plate tectonics.\"".into(),
            topics: vec!["plate tectonics".into(), "geology".into()],
            keywords: vec![
                "plates".into(),
                "continental drift".into(),
                "seafloor spreading".into(),
                "evidence".into(),
            ],
            base_legitimacy: 94,
        },
        IndexedSource {
            id: "amnh-plate-tectonics".into(),
            title: "Plate Tectonics — American Museum of Natural History".into(),
            url: "https://www.amnh.org/exhibitions/permanent/planet-earth/plate-tectonics".into(),
            domain: "amnh.org".into(),
            publisher: "American Museum of Natural History".into(),
            content_tier: AcademicContentTier::EducationalMagazine,
            grade_min: 4,
            grade_max: 9,
            abstract_text: "Museum educators explain how Earth’s plates collide, pull apart, and slide past each other—and how those motions build mountains, open oceans, and trigger earthquakes students can feel in science class.".into(),
            vocabulary: vec![
                "collision".into(),
                "rift".into(),
                "fault".into(),
                "earthquake".into(),
            ],
            citation: "American Museum of Natural History. \"Plate Tectonics.\"".into(),
            topics: vec!["plate tectonics".into(), "earthquakes".into()],
            keywords: vec!["plates".into(), "mountains".into(), "earthquakes".into(), "museum".into()],
            base_legitimacy: 93,
        },
        IndexedSource {
            id: "nasa-earth-dynamic".into(),
            title: "Earth’s Dynamic Surface — NASA Science".into(),
            url: "https://science.nasa.gov/earth/earth-observatory/".into(),
            domain: "science.nasa.gov".into(),
            publisher: "NASA".into(),
            content_tier: AcademicContentTier::AuthoritativeResearch,
            grade_min: 6,
            grade_max: 12,
            abstract_text: "NASA Earth science resources show how satellite observations track plate motion, volcanic ash, and crustal deformation—connecting classroom plate tectonics to real measurements of a living planet.".into(),
            vocabulary: vec![
                "remote sensing".into(),
                "deformation".into(),
                "volcanic ash".into(),
                "crustal motion".into(),
            ],
            citation: "NASA. \"Earth Observatory / Earth Science.\"".into(),
            topics: vec!["plate tectonics".into(), "earth observation".into(), "earth science".into()],
            keywords: vec!["earth".into(), "plates".into(), "satellite".into(), "volcano".into()],
            base_legitimacy: 95,
        },
        IndexedSource {
            id: "noaa-ocean-floor".into(),
            title: "Exploring the Ocean Floor — NOAA".into(),
            url: "https://oceanservice.noaa.gov/facts/plate-boundaries.html".into(),
            domain: "oceanservice.noaa.gov".into(),
            publisher: "NOAA Ocean Service".into(),
            content_tier: AcademicContentTier::VerifiedReference,
            grade_min: 5,
            grade_max: 11,
            abstract_text: "NOAA explains how mapping the ocean floor revealed mid-ocean ridges and trenches—key evidence that plates diverge and converge beneath the sea, powering much of Earth’s tectonic activity.".into(),
            vocabulary: vec![
                "trench".into(),
                "mid-ocean ridge".into(),
                "bathymetry".into(),
                "divergent".into(),
            ],
            citation: "NOAA Ocean Service. \"Plate Boundaries.\"".into(),
            topics: vec!["plate tectonics".into(), "oceanography".into()],
            keywords: vec!["ocean".into(), "ridges".into(), "trenches".into(), "plates".into()],
            base_legitimacy: 95,
        },
        IndexedSource {
            id: "ck12-plate-tectonics".into(),
            title: "Plate Tectonics — CK-12 Earth Science".into(),
            url: "https://www.ck12.org/earth-science/plate-tectonics/".into(),
            domain: "ck12.org".into(),
            publisher: "CK-12 Foundation".into(),
            content_tier: AcademicContentTier::EducationalMagazine,
            grade_min: 6,
            grade_max: 10,
            abstract_text: "A structured lesson on plate tectonics with diagrams of boundary types, practice questions, and vocabulary checks designed for middle and early high school earth science.".into(),
            vocabulary: vec![
                "convergent".into(),
                "divergent".into(),
                "transform".into(),
                "theory".into(),
            ],
            citation: "CK-12 Foundation. \"Plate Tectonics.\"".into(),
            topics: vec!["plate tectonics".into(), "earth science".into()],
            keywords: vec!["plates".into(), "lesson".into(), "boundaries".into(), "classroom".into()],
            base_legitimacy: 86,
        },
        // —— Coral reefs / oceans ——
        IndexedSource {
            id: "noaa-coral-reefs".into(),
            title: "Coral Reefs — NOAA Ocean Service".into(),
            url: "https://oceanservice.noaa.gov/facts/coralreef.html".into(),
            domain: "oceanservice.noaa.gov".into(),
            publisher: "NOAA Ocean Service".into(),
            content_tier: AcademicContentTier::VerifiedReference,
            grade_min: 3,
            grade_max: 10,
            abstract_text: "Coral reefs are underwater ecosystems built by colonies of tiny animals. NOAA describes how reefs form, why they matter for biodiversity and coastal protection, and what threatens them today.".into(),
            vocabulary: vec![
                "polyp".into(),
                "symbiosis".into(),
                "biodiversity".into(),
                "bleaching".into(),
            ],
            citation: "NOAA Ocean Service. \"What is a Coral Reef?\"".into(),
            topics: vec!["coral reefs".into(), "ocean".into(), "ecology".into()],
            keywords: vec!["coral".into(), "reef".into(), "ocean".into(), "habitat".into()],
            base_legitimacy: 95,
        },
        IndexedSource {
            id: "natgeo-kids-coral".into(),
            title: "Coral Reefs — Nat Geo Kids".into(),
            url: "https://kids.nationalgeographic.com/nature/article/coral-reef".into(),
            domain: "kids.nationalgeographic.com".into(),
            publisher: "National Geographic Kids".into(),
            content_tier: AcademicContentTier::EducationalMagazine,
            grade_min: 2,
            grade_max: 6,
            abstract_text: "A kid-friendly tour of coral reef habitats: colorful fish, how polyps build reefs, and why scientists work hard to protect these underwater cities.".into(),
            vocabulary: vec!["coral".into(), "reef".into(), "habitat".into(), "protect".into()],
            citation: "National Geographic Kids. \"Coral Reef.\"".into(),
            topics: vec!["coral reefs".into(), "animals".into(), "ocean".into()],
            keywords: vec!["coral".into(), "reef".into(), "fish".into(), "kids".into()],
            base_legitimacy: 90,
        },
        // —— Solar system ——
        IndexedSource {
            id: "nasa-spaceplace-solar".into(),
            title: "Our Solar System — NASA Space Place".into(),
            url: "https://spaceplace.nasa.gov/menu/solar-system/".into(),
            domain: "spaceplace.nasa.gov".into(),
            publisher: "NASA Space Place".into(),
            content_tier: AcademicContentTier::EducationalMagazine,
            grade_min: 1,
            grade_max: 8,
            abstract_text: "NASA Space Place introduces the Sun, planets, moons, and small bodies with age-appropriate explanations so elementary and middle-grade students can explore astronomy without watered-down dead ends.".into(),
            vocabulary: vec![
                "planet".into(),
                "orbit".into(),
                "moon".into(),
                "asteroid".into(),
                "gravity".into(),
            ],
            citation: "NASA Space Place. \"Solar System.\"".into(),
            topics: vec!["solar system".into(), "planets".into(), "space".into()],
            keywords: vec!["planets".into(), "sun".into(), "space".into(), "orbit".into()],
            base_legitimacy: 94,
        },
        IndexedSource {
            id: "nasa-science-solar".into(),
            title: "Solar System Exploration — NASA Science".into(),
            url: "https://science.nasa.gov/solar-system/".into(),
            domain: "science.nasa.gov".into(),
            publisher: "NASA".into(),
            content_tier: AcademicContentTier::AuthoritativeResearch,
            grade_min: 6,
            grade_max: 12,
            abstract_text: "NASA’s solar system science portal summarizes missions, planetary geology, and current research questions for students ready for deeper space science reading.".into(),
            vocabulary: vec![
                "heliosphere".into(),
                "terrestrial planet".into(),
                "gas giant".into(),
                "mission".into(),
            ],
            citation: "NASA Science. \"Solar System Exploration.\"".into(),
            topics: vec!["solar system".into(), "planets".into(), "space".into()],
            keywords: vec!["planets".into(), "nasa".into(), "exploration".into(), "space".into()],
            base_legitimacy: 97,
        },
        // —— Intentional content-farm decoy (filtered out by legitimacy layer) ——
        IndexedSource {
            id: "farm-tectonics-spam".into(),
            title: "10 Crazy Plate Tectonics Facts That Will Shock You".into(),
            url: "https://viralnova-clickbait.example/plate-tectonics".into(),
            domain: "viralnova-clickbait.example".into(),
            publisher: "Content Farm Demo".into(),
            content_tier: AcademicContentTier::EducationalMagazine,
            grade_min: 1,
            grade_max: 12,
            abstract_text: "Sensationalized non-academic filler designed to be rejected by Surf’s legitimacy filter.".into(),
            vocabulary: vec!["shock".into()],
            citation: "Content Farm Demo.".into(),
            topics: vec!["plate tectonics".into()],
            keywords: vec!["plate".into(), "tectonics".into(), "crazy".into()],
            base_legitimacy: 10,
        },
    ]
}
