import type { Track, UserProfile } from '@/types/models';

/**
 * Seed of recognizable contemporary artists (≈2010–present coverage target).
 * Full Spotify-scale ingest lands via API sync later — this proves the UX:
 * look up Olivia, Sabrina, BVB, Weird Al, etc. alongside unsigned finds.
 */
export const CATALOG_ARTISTS: UserProfile[] = [
  {
    id: 'artist-olivia-rodrigo',
    email: '',
    displayName: 'Olivia Rodrigo',
    role: 'artist',
    scene: 'Pop',
    geography: 'Los Angeles, CA',
    followerCount: 9_200_000,
    bio: 'Diary-pop that defined early-2020s radio.',
    activeYears: '2020–PRESENT',
    status: 'LABEL',
    genreTags: ['Pop', 'Alt-Pop'],
    sceneDescription: 'Mainstream pop / Gen-Z diary rock.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-sabrina-carpenter',
    email: '',
    displayName: 'Sabrina Carpenter',
    role: 'artist',
    scene: 'Pop',
    geography: 'Los Angeles, CA',
    followerCount: 7_400_000,
    bio: 'Sharp hooks, sharper asides.',
    activeYears: '2014–PRESENT',
    status: 'LABEL',
    genreTags: ['Pop', 'Dance-Pop'],
    sceneDescription: 'Contemporary pop / nightlife radio.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-black-veil-brides',
    email: '',
    displayName: 'Black Veil Brides',
    role: 'artist',
    scene: 'Metalcore',
    geography: 'Hollywood, CA',
    followerCount: 1_100_000,
    bio: 'Glam-metalcore that never left the Warped orbit.',
    activeYears: '2006–PRESENT',
    status: 'LABEL',
    genreTags: ['Metalcore', 'Glam Metal', 'Post-Hardcore'],
    sceneDescription: 'Scene / metalcore mainstream.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-weird-al',
    email: '',
    displayName: 'Weird Al Yankovic',
    role: 'artist',
    scene: 'Comedy',
    geography: 'Los Angeles, CA',
    followerCount: 2_800_000,
    bio: 'The parody canon — still touring, still logging hits.',
    activeYears: '1976–PRESENT',
    status: 'LABEL',
    genreTags: ['Comedy', 'Parody', 'Pop'],
    sceneDescription: 'Comedy / parody pop institution.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-billie-eilish',
    email: '',
    displayName: 'Billie Eilish',
    role: 'artist',
    scene: 'Alt-Pop',
    geography: 'Los Angeles, CA',
    followerCount: 11_000_000,
    bio: 'Whisper-pop that flipped the charts.',
    activeYears: '2015–PRESENT',
    status: 'LABEL',
    genreTags: ['Alt-Pop', 'Pop', 'Electronic'],
    sceneDescription: 'Global alt-pop.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-taylor-swift',
    email: '',
    displayName: 'Taylor Swift',
    role: 'artist',
    scene: 'Pop',
    geography: 'Nashville, TN',
    followerCount: 14_000_000,
    bio: 'Catalog eras as cultural weather.',
    activeYears: '2006–PRESENT',
    status: 'LABEL',
    genreTags: ['Pop', 'Indie Folk', 'Country'],
    sceneDescription: 'Stadium pop / re-recording era.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-the-weeknd',
    email: '',
    displayName: 'The Weeknd',
    role: 'artist',
    scene: 'R&B',
    geography: 'Toronto, ON',
    followerCount: 10_500_000,
    bio: 'After-hours R&B that went global.',
    activeYears: '2010–PRESENT',
    status: 'LABEL',
    genreTags: ['R&B', 'Pop', 'Synth'],
    sceneDescription: 'Mainstream R&B / pop noir.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-chappell-roan',
    email: '',
    displayName: 'Chappell Roan',
    role: 'artist',
    scene: 'Pop',
    geography: 'Los Angeles, CA',
    followerCount: 3_200_000,
    bio: 'Midwest princess energy on arena stages.',
    activeYears: '2017–PRESENT',
    status: 'LABEL',
    genreTags: ['Pop', 'Dance-Pop'],
    sceneDescription: '2020s breakout pop.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-charli-xcx',
    email: '',
    displayName: 'Charli XCX',
    role: 'artist',
    scene: 'Hyperpop',
    geography: 'London, UK',
    followerCount: 4_100_000,
    bio: 'Brat summer, forever online.',
    activeYears: '2008–PRESENT',
    status: 'LABEL',
    genreTags: ['Hyperpop', 'Dance-Pop', 'Electronic'],
    sceneDescription: 'Club-pop / hyperpop crossover.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-paramore',
    email: '',
    displayName: 'Paramore',
    role: 'artist',
    scene: 'Pop-Punk',
    geography: 'Franklin, TN',
    followerCount: 5_600_000,
    bio: 'Pop-punk that grew up without getting soft.',
    activeYears: '2004–PRESENT',
    status: 'LABEL',
    genreTags: ['Pop-Punk', 'Alt-Rock', 'Indie'],
    sceneDescription: 'Warped-to-arena pop-punk.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-tame-impala',
    email: '',
    displayName: 'Tame Impala',
    role: 'artist',
    scene: 'Psych',
    geography: 'Perth, AU',
    followerCount: 4_800_000,
    bio: 'Bedroom psych that filled festivals.',
    activeYears: '2007–PRESENT',
    status: 'LABEL',
    genreTags: ['Psych', 'Indie', 'Electronic'],
    sceneDescription: 'Modern psych / festival indie.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-tyler-the-creator',
    email: '',
    displayName: 'Tyler, the Creator',
    role: 'artist',
    scene: 'Hip-Hop',
    geography: 'Los Angeles, CA',
    followerCount: 6_900_000,
    bio: 'Odd Future kid → catalog auteur.',
    activeYears: '2007–PRESENT',
    status: 'LABEL',
    genreTags: ['Hip-Hop', 'Alt-Rap', 'Jazz'],
    sceneDescription: 'Left-field hip-hop / art-rap.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-turnstile',
    email: '',
    displayName: 'Turnstile',
    role: 'artist',
    scene: 'Hardcore',
    geography: 'Baltimore, MD',
    followerCount: 980_000,
    bio: 'Hardcore that crossed into festival daylight.',
    activeYears: '2010–PRESENT',
    status: 'LABEL',
    genreTags: ['Hardcore', 'Punk', 'Alt-Rock'],
    sceneDescription: 'Modern hardcore crossover.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-boygenius',
    email: '',
    displayName: 'boygenius',
    role: 'artist',
    scene: 'Indie',
    geography: 'Los Angeles, CA',
    followerCount: 1_700_000,
    bio: 'Supergroup diary rock.',
    activeYears: '2018–PRESENT',
    status: 'LABEL',
    genreTags: ['Indie', 'Folk', 'Alt-Rock'],
    sceneDescription: 'Indie / folk-rock summit.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-dua-lipa',
    email: '',
    displayName: 'Dua Lipa',
    role: 'artist',
    scene: 'Pop',
    geography: 'London, UK',
    followerCount: 8_100_000,
    bio: 'Disco-revival chart machinery.',
    activeYears: '2015–PRESENT',
    status: 'LABEL',
    genreTags: ['Pop', 'Dance-Pop', 'Disco'],
    sceneDescription: 'Global dance-pop.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-arctic-monkeys',
    email: '',
    displayName: 'Arctic Monkeys',
    role: 'artist',
    scene: 'Indie',
    geography: 'Sheffield, UK',
    followerCount: 7_200_000,
    bio: 'From myspace indie to lounge-rock eras.',
    activeYears: '2002–PRESENT',
    status: 'LABEL',
    genreTags: ['Indie', 'Alt-Rock', 'Psych'],
    sceneDescription: 'UK indie / rock catalog.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-mitski',
    email: '',
    displayName: 'Mitski',
    role: 'artist',
    scene: 'Indie',
    geography: 'New York, NY',
    followerCount: 2_400_000,
    bio: 'Indie that became a generation’s diary.',
    activeYears: '2012–PRESENT',
    status: 'INDEPENDENT',
    genreTags: ['Indie', 'Art Rock'],
    sceneDescription: 'Indie / art-rock.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
  {
    id: 'artist-sleep-token',
    email: '',
    displayName: 'Sleep Token',
    role: 'artist',
    scene: 'Metal',
    geography: 'London, UK',
    followerCount: 1_500_000,
    bio: 'Masked metal that broke the algorithm.',
    activeYears: '2016–PRESENT',
    status: 'LABEL',
    genreTags: ['Metal', 'Alt-Metal', 'Progressive'],
    sceneDescription: 'Modern metal / ritual rock.',
    catalogKind: 'catalog',
    joinedAt: '2010-01-01',
  },
];

export const CATALOG_TRACKS: Track[] = [
  {
    id: 'track-drivers-license',
    title: 'drivers license',
    artistId: 'artist-olivia-rodrigo',
    artistName: 'Olivia Rodrigo',
    downloadUrl: '',
    durationMs: 242000,
    downloadCount: 4_200_000,
    repostCount: 890_000,
    scene: 'Pop',
    geography: 'Los Angeles, CA',
    releaseYear: 2021,
  },
  {
    id: 'track-good-4-u',
    title: 'good 4 u',
    artistId: 'artist-olivia-rodrigo',
    artistName: 'Olivia Rodrigo',
    downloadUrl: '',
    durationMs: 178000,
    downloadCount: 3_800_000,
    repostCount: 720_000,
    scene: 'Pop',
    geography: 'Los Angeles, CA',
    releaseYear: 2021,
  },
  {
    id: 'track-espresso',
    title: 'Espresso',
    artistId: 'artist-sabrina-carpenter',
    artistName: 'Sabrina Carpenter',
    downloadUrl: '',
    durationMs: 175000,
    downloadCount: 5_100_000,
    repostCount: 1_100_000,
    scene: 'Pop',
    geography: 'Los Angeles, CA',
    releaseYear: 2024,
  },
  {
    id: 'track-please-please-please',
    title: 'Please Please Please',
    artistId: 'artist-sabrina-carpenter',
    artistName: 'Sabrina Carpenter',
    downloadUrl: '',
    durationMs: 186000,
    downloadCount: 3_400_000,
    repostCount: 640_000,
    scene: 'Pop',
    geography: 'Los Angeles, CA',
    releaseYear: 2024,
  },
  {
    id: 'track-knives-and-pens',
    title: 'Knives and Pens',
    artistId: 'artist-black-veil-brides',
    artistName: 'Black Veil Brides',
    downloadUrl: '',
    durationMs: 248000,
    downloadCount: 920_000,
    repostCount: 210_000,
    scene: 'Metalcore',
    geography: 'Hollywood, CA',
    releaseYear: 2010,
  },
  {
    id: 'track-in-the-end-bvb',
    title: 'In the End',
    artistId: 'artist-black-veil-brides',
    artistName: 'Black Veil Brides',
    downloadUrl: '',
    durationMs: 227000,
    downloadCount: 780_000,
    repostCount: 155_000,
    scene: 'Metalcore',
    geography: 'Hollywood, CA',
    releaseYear: 2012,
  },
  {
    id: 'track-word-crimes',
    title: 'Word Crimes',
    artistId: 'artist-weird-al',
    artistName: 'Weird Al Yankovic',
    downloadUrl: '',
    durationMs: 223000,
    downloadCount: 640_000,
    repostCount: 98_000,
    scene: 'Comedy',
    geography: 'Los Angeles, CA',
    releaseYear: 2014,
  },
  {
    id: 'track-white-willy',
    title: 'White & Nerdy',
    artistId: 'artist-weird-al',
    artistName: 'Weird Al Yankovic',
    downloadUrl: '',
    durationMs: 170000,
    downloadCount: 1_200_000,
    repostCount: 240_000,
    scene: 'Comedy',
    geography: 'Los Angeles, CA',
    releaseYear: 2006,
  },
  {
    id: 'track-bad-guy',
    title: 'bad guy',
    artistId: 'artist-billie-eilish',
    artistName: 'Billie Eilish',
    downloadUrl: '',
    durationMs: 194000,
    downloadCount: 6_200_000,
    repostCount: 1_400_000,
    scene: 'Alt-Pop',
    geography: 'Los Angeles, CA',
    releaseYear: 2019,
  },
  {
    id: 'track-anti-hero',
    title: 'Anti-Hero',
    artistId: 'artist-taylor-swift',
    artistName: 'Taylor Swift',
    downloadUrl: '',
    durationMs: 200000,
    downloadCount: 7_800_000,
    repostCount: 1_900_000,
    scene: 'Pop',
    geography: 'Nashville, TN',
    releaseYear: 2022,
  },
  {
    id: 'track-blinding-lights',
    title: 'Blinding Lights',
    artistId: 'artist-the-weeknd',
    artistName: 'The Weeknd',
    downloadUrl: '',
    durationMs: 200000,
    downloadCount: 9_100_000,
    repostCount: 2_200_000,
    scene: 'R&B',
    geography: 'Toronto, ON',
    releaseYear: 2019,
  },
  {
    id: 'track-good-luck-babe',
    title: 'Good Luck, Babe!',
    artistId: 'artist-chappell-roan',
    artistName: 'Chappell Roan',
    downloadUrl: '',
    durationMs: 218000,
    downloadCount: 2_900_000,
    repostCount: 710_000,
    scene: 'Pop',
    geography: 'Los Angeles, CA',
    releaseYear: 2024,
  },
  {
    id: 'track-365',
    title: '365',
    artistId: 'artist-charli-xcx',
    artistName: 'Charli XCX',
    downloadUrl: '',
    durationMs: 201000,
    downloadCount: 1_800_000,
    repostCount: 430_000,
    scene: 'Hyperpop',
    geography: 'London, UK',
    releaseYear: 2024,
  },
  {
    id: 'track-this-is-why',
    title: 'This Is Why',
    artistId: 'artist-paramore',
    artistName: 'Paramore',
    downloadUrl: '',
    durationMs: 212000,
    downloadCount: 1_100_000,
    repostCount: 260_000,
    scene: 'Pop-Punk',
    geography: 'Franklin, TN',
    releaseYear: 2023,
  },
  {
    id: 'track-the-less-i-know',
    title: 'The Less I Know The Better',
    artistId: 'artist-tame-impala',
    artistName: 'Tame Impala',
    downloadUrl: '',
    durationMs: 216000,
    downloadCount: 3_600_000,
    repostCount: 880_000,
    scene: 'Psych',
    geography: 'Perth, AU',
    releaseYear: 2015,
  },
  {
    id: 'track-see-you-again-tyler',
    title: 'See You Again',
    artistId: 'artist-tyler-the-creator',
    artistName: 'Tyler, the Creator',
    downloadUrl: '',
    durationMs: 180000,
    downloadCount: 2_700_000,
    repostCount: 610_000,
    scene: 'Hip-Hop',
    geography: 'Los Angeles, CA',
    releaseYear: 2017,
  },
  {
    id: 'track-holiday-turnstile',
    title: 'HOLIDAY',
    artistId: 'artist-turnstile',
    artistName: 'Turnstile',
    downloadUrl: '',
    durationMs: 166000,
    downloadCount: 540_000,
    repostCount: 120_000,
    scene: 'Hardcore',
    geography: 'Baltimore, MD',
    releaseYear: 2021,
  },
  {
    id: 'track-not-strong-enough',
    title: 'Not Strong Enough',
    artistId: 'artist-boygenius',
    artistName: 'boygenius',
    downloadUrl: '',
    durationMs: 239000,
    downloadCount: 980_000,
    repostCount: 205_000,
    scene: 'Indie',
    geography: 'Los Angeles, CA',
    releaseYear: 2023,
  },
  {
    id: 'track-levitating',
    title: 'Levitating',
    artistId: 'artist-dua-lipa',
    artistName: 'Dua Lipa',
    downloadUrl: '',
    durationMs: 203000,
    downloadCount: 5_400_000,
    repostCount: 1_050_000,
    scene: 'Pop',
    geography: 'London, UK',
    releaseYear: 2020,
  },
  {
    id: 'track-do-i-wanna-know',
    title: 'Do I Wanna Know?',
    artistId: 'artist-arctic-monkeys',
    artistName: 'Arctic Monkeys',
    downloadUrl: '',
    durationMs: 272000,
    downloadCount: 4_900_000,
    repostCount: 1_150_000,
    scene: 'Indie',
    geography: 'Sheffield, UK',
    releaseYear: 2013,
  },
  {
    id: 'track-nobody',
    title: 'Nobody',
    artistId: 'artist-mitski',
    artistName: 'Mitski',
    downloadUrl: '',
    durationMs: 201000,
    downloadCount: 1_600_000,
    repostCount: 390_000,
    scene: 'Indie',
    geography: 'New York, NY',
    releaseYear: 2018,
  },
  {
    id: 'track-the-summoning',
    title: 'The Summoning',
    artistId: 'artist-sleep-token',
    artistName: 'Sleep Token',
    downloadUrl: '',
    durationMs: 393000,
    downloadCount: 1_250_000,
    repostCount: 310_000,
    scene: 'Metal',
    geography: 'London, UK',
    releaseYear: 2023,
  },
];
