#!/usr/bin/env node
/**
 * Interactive-ish env bootstrap: prints a ready-to-paste .env block.
 * Usage: npm run setup:env
 */
import { randomBytes } from "node:crypto";
import { readFileSync, existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const secret = randomBytes(32).toString("base64");
const root = resolve(process.cwd());
const envPath = resolve(root, ".env");

const block = `# Generated by npm run setup:env — fill remaining partner keys
DATABASE_URL="file:./dev.db"
# Production:
# DATABASE_URL="postgresql://USER:PASS@HOST:5432/trumprx?sslmode=require"

AUTH_SECRET="${secret}"
AUTH_URL="http://localhost:3000"
NEXT_PUBLIC_APP_URL="http://localhost:3000"
NEXT_PUBLIC_APP_NAME="Trump RX"

TRUMPRX_BIN="610020"
TRUMPRX_PCN="TRUMPRX"
TRUMPRX_GROUP="TRXSAVE"
COUPON_TTL_HOURS="72"
PRICING_PROVIDER="network"

# Staff chat inbox + alerts
ADMIN_EMAILS="you@yourdomain.com"
# RESEND_API_KEY=
# RESEND_FROM_EMAIL="alerts@yourdomain.com"
# ADMIN_SMS_TO="+1..."

# Stripe
# STRIPE_SECRET_KEY=
# STRIPE_WEBHOOK_SECRET=
# STRIPE_PLUS_PRICE_ID=
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=

# Live partners
# SWITCH_API_URL=
# SWITCH_API_KEY=
# PRICING_PROVIDER="external"
# PRICING_API_URL=
# TELEHEALTH_PARTNER_URL=
# MAIL_ORDER_PARTNER_URL=

# SENTRY_DSN=
`;

console.log("=== Trump RX env bootstrap ===\n");
console.log(block);

if (!existsSync(envPath)) {
  writeFileSync(envPath, block, "utf8");
  console.log(`Wrote ${envPath}`);
} else {
  const current = readFileSync(envPath, "utf8");
  if (!current.includes("AUTH_SECRET=") || /AUTH_SECRET=\s*$/m.test(current) || /AUTH_SECRET=""/.test(current)) {
    console.log(
      "\n.env exists. Paste AUTH_SECRET below into your file if empty:\n"
    );
    console.log(`AUTH_SECRET="${secret}"`);
  } else {
    console.log("\n.env already has AUTH_SECRET — left file unchanged.");
  }
}

console.log("\nNext:");
console.log("  1. Fill ADMIN_EMAILS + Resend for chat alerts");
console.log("  2. npm run db:use-postgres   # before production Postgres");
console.log("  3. Open /admin/launch after signing in as an admin");
