import type { FamilyChart } from "./types";

/**
 * Fictional family used when the app is not connected to a health system.
 * Names, record numbers, and clinical details are invented sample data.
 */
export const DEMO_FAMILY: FamilyChart = {
  guardian: {
    id: "jordan",
    name: "Jordan Hale",
    email: "jordan.hale@example.com",
    relationship: "Parent",
  },
  children: [
    {
      child: {
        id: "maya",
        name: "Maya Hale",
        preferredName: "Maya",
        birthDate: "2018-06-02",
        sex: "female",
        mrn: "MC-204918",
        initials: "MH",
        color: "#1F7A8C",
      },
      visits: [
        {
          id: "maya-well",
          patientId: "maya",
          status: "booked",
          kind: "well-visit",
          title: "Annual well visit",
          reason: "Yearly checkup and school form",
          start: "2026-10-02T13:20:00Z",
          end: "2026-10-02T13:50:00Z",
          provider: "Amira Shah, MD",
          specialty: "Pediatrics",
          location: "Harbor Pediatrics",
          address: "18 Brookline Place, Boston, MA",
          instructions: [
            "Bring a photo ID and the insurance card.",
            "Bring the inhaler Maya uses at school.",
            "eCheck-In is open for this visit.",
          ],
        },
        {
          id: "maya-strep",
          patientId: "maya",
          status: "fulfilled",
          kind: "sick",
          title: "Sore throat visit",
          reason: "Sore throat and cough",
          start: "2026-09-12T14:10:00Z",
          end: "2026-09-12T14:30:00Z",
          provider: "Amira Shah, MD",
          specialty: "Pediatrics",
          location: "Harbor Pediatrics",
          address: "18 Brookline Place, Boston, MA",
          instructions: [],
          summary:
            "Rapid strep testing was negative. Maya was drinking fluids comfortably. The clinic note says to continue the asthma medicines already on her list and to return if breathing becomes difficult.",
        },
      ],
      results: [
        {
          id: "maya-eos",
          patientId: "maya",
          name: "Eosinophils",
          panel: "Complete blood count",
          collectedAt: "2026-06-11T13:05:00Z",
          reportedAt: "2026-06-11T16:40:00Z",
          status: "final",
          value: "0.8",
          unit: "10^3/µL",
          referenceRange: "0.0–0.5",
          interpretation: "high",
          note: "Reviewed with the allergy plan already on file.",
        },
        {
          id: "maya-hgb",
          patientId: "maya",
          name: "Hemoglobin",
          panel: "Complete blood count",
          collectedAt: "2026-06-11T13:05:00Z",
          reportedAt: "2026-06-11T16:40:00Z",
          status: "final",
          value: "12.8",
          unit: "g/dL",
          referenceRange: "11.5–14.5",
          interpretation: "normal",
        },
        {
          id: "maya-wbc",
          patientId: "maya",
          name: "White blood cells",
          panel: "Complete blood count",
          collectedAt: "2026-06-11T13:05:00Z",
          reportedAt: "2026-06-11T16:40:00Z",
          status: "final",
          value: "8.4",
          unit: "10^3/µL",
          referenceRange: "5.0–14.5",
          interpretation: "normal",
        },
        {
          id: "maya-strep-result",
          patientId: "maya",
          name: "Rapid strep",
          panel: "Respiratory",
          collectedAt: "2026-09-12T14:20:00Z",
          reportedAt: "2026-09-12T14:28:00Z",
          status: "final",
          value: "Negative",
          interpretation: "normal",
        },
      ],
      medications: [
        {
          id: "maya-albuterol",
          patientId: "maya",
          name: "Albuterol HFA 90 mcg inhaler",
          status: "active",
          prescriber: "Amira Shah, MD",
          startedOn: "2024-09-01",
          instructions: "2 puffs every 4 hours as needed for cough or wheeze.",
        },
        {
          id: "maya-fluticasone",
          patientId: "maya",
          name: "Fluticasone 44 mcg inhaler",
          status: "active",
          prescriber: "Amira Shah, MD",
          startedOn: "2024-09-01",
          instructions: "2 puffs twice a day.",
        },
        {
          id: "maya-cetirizine",
          patientId: "maya",
          name: "Cetirizine 5 mg chewable",
          status: "active",
          prescriber: "Helen Cho, MD",
          startedOn: "2025-04-02",
          instructions: "1 tablet at night during allergy season.",
        },
      ],
      vaccines: [
        {
          id: "maya-flu-due",
          patientId: "maya",
          name: "Influenza",
          status: "due",
          doseLabel: "2026–2027 season",
        },
        {
          id: "maya-flu-done",
          patientId: "maya",
          name: "Influenza",
          status: "completed",
          date: "2025-10-18",
          doseLabel: "2025–2026 season",
        },
        {
          id: "maya-mmr",
          patientId: "maya",
          name: "MMR",
          status: "completed",
          date: "2022-06-20",
          doseLabel: "Dose 2",
        },
        {
          id: "maya-dtap",
          patientId: "maya",
          name: "DTaP",
          status: "completed",
          date: "2022-06-20",
          doseLabel: "Dose 5",
        },
      ],
      allergies: [
        {
          id: "maya-peanut",
          patientId: "maya",
          substance: "Peanuts",
          reaction: "Anaphylaxis",
          severity: "severe",
          status: "active",
        },
        {
          id: "maya-penicillin",
          patientId: "maya",
          substance: "Penicillin",
          reaction: "Hives",
          severity: "moderate",
          status: "active",
        },
      ],
      conditions: [
        {
          id: "maya-asthma",
          patientId: "maya",
          name: "Mild persistent asthma",
          status: "active",
          onset: "2023-04-12",
        },
      ],
      growth: [
        {
          id: "maya-g1",
          patientId: "maya",
          date: "2024-06-01",
          heightCm: 122,
          heightPercentile: 55,
          weightKg: 23.1,
          weightPercentile: 50,
        },
        {
          id: "maya-g2",
          patientId: "maya",
          date: "2025-06-04",
          heightCm: 128.4,
          heightPercentile: 60,
          weightKg: 25.4,
          weightPercentile: 52,
        },
        {
          id: "maya-g3",
          patientId: "maya",
          date: "2026-06-11",
          heightCm: 134.2,
          heightPercentile: 62,
          weightKg: 28,
          weightPercentile: 58,
        },
      ],
      messages: [
        {
          id: "msg-prep",
          patientId: "maya",
          threadId: "thread-prep",
          subject: "Before Friday's visit",
          fromName: "Amira Shah, MD",
          fromRole: "Pediatrics",
          sentAt: "2026-09-25T18:12:00Z",
          body: "We will update Maya's growth measurements and vaccines at the well visit. Write down any questions you want to cover.",
          unread: false,
          direction: "in",
        },
        {
          id: "msg-asthma",
          patientId: "maya",
          threadId: "thread-asthma",
          subject: "School asthma form",
          fromName: "Luis Ortega, RN",
          fromRole: "Care coordinator",
          sentAt: "2026-09-28T15:04:00Z",
          body: "Please bring Maya's school asthma form to Friday's well visit. We can review it with Dr. Shah and send a copy to the school after the visit.",
          unread: true,
          direction: "in",
        },
      ],
      bills: [
        {
          id: "bill-maya-sep",
          patientId: "maya",
          description: "Office visit",
          serviceDate: "2026-09-12",
          amountCents: 3000,
          status: "due",
        },
      ],
      careTeam: [
        {
          id: "maya-shah",
          patientId: "maya",
          name: "Amira Shah, MD",
          role: "Primary pediatrician",
          clinic: "Harbor Pediatrics",
        },
        {
          id: "maya-ortega",
          patientId: "maya",
          name: "Luis Ortega, RN",
          role: "Care coordinator",
          clinic: "Harbor Pediatrics",
        },
        {
          id: "maya-cho",
          patientId: "maya",
          name: "Helen Cho, MD",
          role: "Allergy",
          clinic: "Harbor Pediatrics",
        },
      ],
    },
    {
      child: {
        id: "leo",
        name: "Leo Hale",
        preferredName: "Leo",
        birthDate: "2024-03-18",
        sex: "male",
        mrn: "MC-338102",
        initials: "LH",
        color: "#C46B3A",
      },
      visits: [
        {
          id: "leo-well",
          patientId: "leo",
          status: "booked",
          kind: "well-visit",
          title: "Well visit",
          reason: "Routine checkup",
          start: "2026-10-20T14:00:00Z",
          end: "2026-10-20T14:30:00Z",
          provider: "Amira Shah, MD",
          specialty: "Pediatrics",
          location: "Harbor Pediatrics",
          address: "18 Brookline Place, Boston, MA",
          instructions: [
            "Bring a photo ID and the insurance card.",
            "eCheck-In opens seven days before the visit.",
          ],
        },
        {
          id: "leo-ear",
          patientId: "leo",
          status: "fulfilled",
          kind: "follow-up",
          title: "Ear check",
          reason: "Follow-up after an ear infection",
          start: "2026-09-09T15:00:00Z",
          end: "2026-09-09T15:20:00Z",
          provider: "Amira Shah, MD",
          specialty: "Pediatrics",
          location: "Harbor Pediatrics",
          address: "18 Brookline Place, Boston, MA",
          instructions: [],
          summary:
            "The clinic note says Leo's ear looked clear and the antibiotic course was finished. Call the clinic if a fever returns.",
        },
      ],
      results: [
        {
          id: "leo-flu",
          patientId: "leo",
          name: "Rapid influenza",
          panel: "Respiratory",
          collectedAt: "2026-09-08T16:00:00Z",
          reportedAt: "2026-09-08T16:12:00Z",
          status: "final",
          value: "Negative",
          interpretation: "normal",
        },
      ],
      medications: [
        {
          id: "leo-amox",
          patientId: "leo",
          name: "Amoxicillin 400 mg/5 mL",
          status: "completed",
          prescriber: "Amira Shah, MD",
          startedOn: "2026-08-26",
          instructions: "5 mL twice a day for 7 days. Course finished.",
        },
      ],
      vaccines: [
        {
          id: "leo-hepa",
          patientId: "leo",
          name: "Hepatitis A",
          status: "overdue",
          doseLabel: "Dose 2",
        },
        {
          id: "leo-flu",
          patientId: "leo",
          name: "Influenza",
          status: "due",
          doseLabel: "2026–2027 season",
        },
        {
          id: "leo-mmr",
          patientId: "leo",
          name: "MMR",
          status: "completed",
          date: "2025-03-20",
          doseLabel: "Dose 1",
        },
        {
          id: "leo-dtap",
          patientId: "leo",
          name: "DTaP",
          status: "completed",
          date: "2024-09-18",
          doseLabel: "Dose 3",
        },
      ],
      allergies: [],
      conditions: [
        {
          id: "leo-ear-dx",
          patientId: "leo",
          name: "Acute otitis media",
          status: "resolved",
          onset: "2026-08-26",
        },
      ],
      growth: [
        {
          id: "leo-g1",
          patientId: "leo",
          date: "2025-03-18",
          heightCm: 76,
          heightPercentile: 48,
          weightKg: 10.1,
          weightPercentile: 45,
        },
        {
          id: "leo-g2",
          patientId: "leo",
          date: "2025-09-20",
          heightCm: 82,
          heightPercentile: 50,
          weightKg: 11.4,
          weightPercentile: 47,
        },
        {
          id: "leo-g3",
          patientId: "leo",
          date: "2026-03-19",
          heightCm: 87.5,
          heightPercentile: 52,
          weightKg: 12.6,
          weightPercentile: 49,
        },
      ],
      messages: [
        {
          id: "msg-ear",
          patientId: "leo",
          threadId: "thread-ear",
          subject: "Ear check follow-up",
          fromName: "Amira Shah, MD",
          fromRole: "Pediatrics",
          sentAt: "2026-09-09T18:40:00Z",
          body: "Leo's ear looked clear at today's visit. The antibiotic course on his chart is finished. Call the clinic if a fever comes back.",
          unread: false,
          direction: "in",
        },
      ],
      bills: [
        {
          id: "bill-leo-sep",
          patientId: "leo",
          description: "Ear check balance",
          serviceDate: "2026-09-09",
          amountCents: 1500,
          status: "due",
        },
      ],
      careTeam: [
        {
          id: "leo-shah",
          patientId: "leo",
          name: "Amira Shah, MD",
          role: "Primary pediatrician",
          clinic: "Harbor Pediatrics",
        },
        {
          id: "leo-raman",
          patientId: "leo",
          name: "Priya Raman, RN",
          role: "Clinic nurse",
          clinic: "Harbor Pediatrics",
        },
      ],
    },
  ],
};
